###
# This parameter specifies the root url for the RestApi endpoints.
# Should not have a trailing "/"
API_ENDPOINT: "https://api.vhh-mmsi.eu/api/tbaservice"   # root url for API endpoints

###
# Path to the folder which will store the data
DATA_PATH: "/data/share/fjogl/vhh_rd_data"

###
# Path to the directory that contains the videos
VIDEO_PATH: "/data/ext/VHH/release_results/release_v1_3_0/vhh_core/videos_part1/"

###
# Path to the directory that contains the shot information
SHOT_PATH: "/data/ext/VHH/release_results/release_v1_3_0/vhh_core/results_part1/sbd/final_results"

###
# Model to use for feature extractor (resnet152, resnet50)
MODEL: "resnet50"

###
# Siamese
SIAMESE: True


###
# Distance metric used to compute similarities (euclidean, manhattan, chebyshev, minkowski)
DISTANCE_METRIC: "cosine"


###
# Additional metric parameter, only used for minkowski
METRIC_PARAM: 20

###
# Batchsize for inference
BATCHSIZE: 64

###########################################
#
# PARAMETERS FOR TRAINING SIAMESE NET
#
###########################################

###
# Path to the siamese net data (images)
SIAM_TRAIN_PATH: "/caa/Projects02/vhh/private/database_nobackup/stc_vhh_mmsi_1_3_0/stc_vhh_mmsi_v1_3_0/train"
SIAM_VAL_PATH: "/caa/Projects02/vhh/private/database_nobackup/stc_vhh_mmsi_1_3_0/stc_vhh_mmsi_v1_3_0/val"
SIAM_TEST_PATH: "/caa/Projects02/vhh/private/database_nobackup/stc_vhh_mmsi_1_3_0/stc_vhh_mmsi_v1_3_0/test"

###
# Batchsize during training
BATCHSIZE_TRAIN: 4

###
# Batchsize during training
BATCHSIZE_EVALUATE: 16

###
# Number of epochs
NR_EPOCHS: 100

###
# Loss type to use during training (triplet, cosine)
LOSS_TYPE: "cosine"

###
# After this number of epochs without improvement the training will stop and the best model will be loaded
EPOCHS_EARLY_STPOPPING: 5

###
# Nummer of workers for data preparation 
NUM_WORKERS_TRAINING: 6